baseURL = "https://schwemmecomics.github.io/schwemme-comic/"
languageCode = "de-de"
title = "Schwemme Comics"
#theme = "schwemme-theme"

# Spracheinstellungen
defaultContentLanguage = "de"
[languages]
  # --- DEUTSCH ---
[languages.de]
  languageName = "Deutsch"
  weight = 1
  # Hier kommen die deutschen Menüpunkte drunter:
    [[languages.de.menu.main]]
    name = "Aktuelles"
    url = "/news/"
    weight = 1
  [[languages.de.menu.main]]
    name = "Archiv"
    url = "/comics/"
    weight = 2
  [[languages.de.menu.main]]
    name = "Charaktere"
    url = "/characters/"
    weight = 3
  [[languages.de.menu.main]]
    name = "Kreativarbeit"
    url = "/creative/"
    weight = 4
  [[languages.de.menu.main]]
    name = "Über mich"
    url = "/about/"
    weight = 5

# --- ENGLISCH ---
[languages.en]
  languageName = "English"
  weight = 2
  # Hier kommen die englischen Menüpunkte drunter:
  [[languages.en.menu.main]]
    name = "News"
    url = "/en/news/"
    weight = 1
  [[languages.en.menu.main]]
    name = "Archive"
    url = "/en/comics/"
    weight = 2
  [[languages.en.menu.main]]
    name = "Characters"
    url = "/en/characters/"
    weight = 3
  [[languages.en.menu.main]]
    name = "Creative Work"
    url = "/en/creative/"
    weight = 4
  [[languages.en.menu.main]]
    name = "About Me"
    url = "/en/about/"
    weight = 5

[params]
  description = "Comics von Ernestito"
  header_image = "images/header.png"
  # Akzentfarben
  color_accent = "#004488" # Dunkelblau
  color_hover = "#FFD700"  # Goldgelb
  
  # Navigation Icons
  icon_first = "images/first.png"
  icon_prev = "images/previous.png"
  icon_random = "images/random.png"
  icon_next = "images/next.png"
  icon_last = "images/last.png"

  # Share Icon
  icon_share = "images/share.png" 


  # Disclaimer Footer
  disclaimer = "Alle Charaktere und Ereignisse in diesem Comic sind fiktiv. Ähnlichkeiten mit lebenden oder verstorbenen Personen oder Ereignissen sind rein zufällig."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
