baseURL = "https://schwemmecomics.github.io/schwemme-comic/"
languageCode = "de-de"
title = "Schwemme Comics"
#theme = "schwemme-theme"

# Spracheinstellungen
defaultContentLanguage = "de"
[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2

[params]
  description = "Comics von Ernestito"
  header_image = "images/header.png"
  # Akzentfarben
  color_accent = "#004488" # Dunkelblau
  color_hover = "#FFD700"  # Goldgelb
  
  # Navigation Icons
  icon_first = "images/first.png"
  icon_prev = "images/previous.png"
  icon_random = "images/random.png"
  icon_next = "images/next.png"
  icon_last = "images/last.png"

  # Disclaimer Footer
  disclaimer = "Alle Charaktere und Ereignisse in diesem Comic sind fiktiv. Ähnlichkeiten mit lebenden oder verstorbenen Personen oder Ereignissen sind rein zufällig."

[[menu.main]]
    name = "Comics"
    url = "/comics/"
    weight = 1
[[menu.main]]
    name = "Archiv"
    url = "/archive/"
    weight = 2
[[menu.main]]
    name = "Charaktere"
    url = "/characters/"
    weight = 3
[[menu.main]]
    name = "Kreativarbeit"
    url = "/creative/"
    weight = 4
[[menu.main]]
    name = "Über mich"
    url = "/about/"
    weight = 5
